- src/IIIF.php
This adds a `seeAlso` property to the presentation manifest according to [prez v3](https://iiif.io/api/presentation/3.0/#seealso). 
I assumed that private methods in PHP are similar to private methods in other languages I know and that private methods are available to the instance of the class but not external to the class.  Since I have no idea why this would need to be open external to the class, I made it private although this seems to differ from other methods in the class.  If I've misunderstood this, things may not work.
I did not.  I read the README, but I felt like there was something I was missing.
I'm rexploring change discovery and thinking about a presentation for next week.  While rereading the specifications, I remembered that applications that consume IIIF manifests and …
> Add buildSeeAlso method.

- src/IIIF.php
Changes label from "Role Term" to  "Creators and Contributors" and attempts to stop key value pairs with empty arrays from getting into manifests.
The original plan was grab all `//mods/name` values and associate them base on the value of `role/roleTerm`.  The value of `role/roleTerm` would be the label and the value of `namePart` would be represented in the value.  This doesn't attempt to do this, but instead simply switches the label to Creators and Contributors.  We can revisit this later if necessary.
Currently, empty arrays are getting into the final manifest even thought validateMetadata() attempts to stop this.  This change attempts to fix this.  An example is [tenncities:343](https://digital.lib.utk.edu/assemble/manifest/tenncities/343).
No, I still can't get the dev environment …
> Switch role term label and add additional check.

- README.md
- src/Collection.php
- src/IIIF.php
- src/Manifest.php
- src/Request.php
- src/Utility.php
Addresses https://jirautk.atlassian.net/browse/DIGITAL-1130
This adds a Collection class to the assemble application, allowing for creation of on the fly collections according to the[Presentation 3.0 API](https://iiif.io/api/presentation/3.0/#51-collectioncollections). 
Because these collections are not yet intended to be shared publicly, I approached this to only meet the MUSTs of specification. In addition, I limited the `label` of each collection item to the PID returned from RISearch. Retrieval of the actual title of each object as the label would require an additional API request for each item.
If you have the [utk_digital](https://github.com/utkdigitalinitiatives/utk_digital) Vagrant running locally, resolve to a URL where the pattern of the collection PID is …
> Generate IIIF Collections (Presentation 3)

- src/IIIF.php
This sets the correct access level DSID to be mapped to the IIIF Manifest for items with the type of **Sound** and **Video**. Type is determined by the object model at https://github.com/utkdigitalinitiatives/iiif_assemble/blob/main/src/IIIF.php#L515-L537.
If you have the [utk_digital](https://github.com/utkdigitalinitiatives/utk_digital) Vagrant running locally, resolve to a URL where the pattern of the collection PID is `/assemble/manifest/{namespace}/{id}`. Reference a PID with an model of either `islandora:sp-audioCModel` or `islandora:sp_videoCModel` objects having `PROXY_MP3` or `MP4` datastreams. The manifest should not reference an OBJ in the **items** property tree, If you want to, go a step further and test this in a viewer.
> Set Sound/Video type to proxy dsid URI.

- src/IIIF.php
[DIGITAL-1153](https://jirautk.atlassian.net/browse/DIGITAL-1153)
This makes it so that a value must be not null and not empty to be split into descriptive metadata elements.  Previously, only one had to be true.
If you have the utk_digital Vagrant running locally, replace the MODS of a current object with one from rfta.  Before pulling this branch in, you should see it has an empty value for the matching "Publication Identifier" label.  On replace with this branch, it will not.
> Fix logic when testing for empty values.

- src/IIIF.php
- src/Request.php
- src/Utility.php
[DIGITAL-1133](https://jirautk.atlassian.net/browse/DIGITAL-1133)
[EXHIBIT-79](https://jirautk.atlassian.net/browse/EXHIBIT-79)
This adds a label to canvases in the manifest using the value of the page titles from Risearch.
The standard query to Risearch for pages belonging to books now includes titles with the pids and the page numbers.  Code has been refactored to handle this modification so that it has no side effects.
This should add a label to each canvas with a language of `none` like so:
To test, use assemble in the utk_digital vagrant and point at a book-like object.  Use Islandora Sample Content Generator if you need one to test.
As seen in [EXHIBIT-79](https://jirautk.atlassian.net/browse/EXHIBIT-79), we currently have an error in Mirador gallery view.
~~Probably.  This work is …
> Address DIGITAL-1133 and EXHIBIT-79.

- src/IIIF.php
- src/Request.php
This adds transcripts to Islandora Audio and Video objects if they exist. If an object has a TRANSCRIPT or TRANSCRIPT-ES datastream and its type is identified as "Sound" or "Video", the appropriate transcript(s) is added.
This uses the Fedora resource index to determine the datastreams associated with a particular object.  Then, when items are getting added to the AnnotationPage, we add additional items with the motivation of supplementing to the function that paints the primary canvas.
Yep
Yep
I haven't tested this in Mirador to see what happens. For some reason, I get an error trying to spin up my local copy.
> Address DIGITAL-1154.

- src/IIIF.php
[DIGITAL-1168](https://jirautk.atlassian.net/browse/DIGITAL-1168)
Initially, a decision was made to set the partType attribute in the pbcore as `iiif`. This was altered in the past few months to be specific to the RFTA values of **Chapters**, **Interview Questions**, and **geographic**. This pull request addresses that change and only allows pbcore parts with the partType of **Chapters** and **Interview Questions** to render to structures.
Grab a MODS record that has pbcore with partTypes of **Chapters**, **Interview Questions**, and **geographic**. Structures will output in the manifest with multiple rangers for just the allowed types iof **Chapters** and **Interview Questions**.
Note: This does not address any issue related to the the temporal dimension media fragment.
> Make range generating conditional specific to RFTA partType values.

- src/IIIF.php
- src/Request.php
Adds a "Type of Resource" metadata value to the manifest based on the type of the resource.
Readds a method that we accidentally deleted earlier this week.
Look at metadata values.  Is there a typeOfResource?
Are things generating correctly.
> Add type of resource to metadata.

- src/IIIF.php
1. Adds abstract to metadata.
2. Adds a Spanish abstract and Spanish title to metadata.
3. Refactors things to allow for metadata elements to be in other languages. (not a great approach, but okay for now).
4. Only allows for labels in English (for now).
Check this branch out in utk_digital and do an update on an object with a Spanish RFTA MODS record.  Look at the updated manifest in assemble.
> Add Abstract and other things to manifest.

- src/IIIF.php
Adds Browse as a Field in the `metadata` property.
We will update the xpath here.
> Add browse as a field.

- src/IIIF.php
1. Adds an easy solution for fixing problems in Canopy for valid metadata.
2. Allows us to switch values on the fly.
Don't.  It seems like getting a test framework for this is too difficult for people.  I'll own that.
Just read the code and make sure you understand what's happening and let me know if you have questions.
> Fix browse

- src/IIIF.php
Adds language  to metadata property in each manifest.
If there is a defined language, we copy those over.  If there isn't, we write English
The RFTA team has asked to build a facet to limit languages on, but currently we have nothing in the manifest to base this on.  This adds that.
Spin up utk_digital, add an object, add a MODS record from UTK (with or without a language), do a `get` request on the object with cache update command. Something like:
`http://localhost:8000/assemble/manifest/test/2?update=1`
Look for language in the `metadata` property.
> Address DIGITAL-1329: add language to manifest.

- src/IIIF.php
Adds an `accompanyingCanvas` for Sound manifests.
In Canopy, our viewer needs to display an image agnostic ally for sound things.  Following presentation v3, this should be done with the `accompanyingCanvas` property.  You can read more about it here and its rules:
https://iiif.io/api/presentation/3.0/#accompanyingcanvas
The work here is largely a take on this recipe published by the IIIF community:
https://iiif.io/api/cookbook/recipe/0014-accompanyingcanvas/
From the recipe is a very close example of what we're trying to do here:
> You might want to have an image available while an audio-only Canvas is playing or, conversely, audio available while a user is navigating an image-only Manifest.
That will be handled in a later pull request to that repo to leverage work here.
Well ....
It's …
> Address Digital-1182.

- src/Collection.php
- src/IIIF.php
- src/Request.php
- src/Utility.php
This uses the label for an object from RISearch as the label of an object in a collection manifest instead of the PID.  It also changes the return for a failed collection request.
You can test locally or do it live:
While on the current branch `main`, look at the collection manifest for your favorite collection.  Something like:
https://digital.lib.utk.edu/assemble/collection/collections/rfta?update=1
Checkout the label associated with a manifest that belongs to the collection:
Notice that the label is the PID. 🤮 
Now, checkout the current branch and look at the same thing:
https://digital.lib.utk.edu/assemble/collection/collections/rfta?update=1
No, but it's definitely a quality of life improvement.  Also, more in line with spec in my opinion.
> Address DIGITAL-1380.

- src/IIIF.php
- src/Request.php
- src/XPath.php
This pull request does several things:
1. Adds thumbnails to Manifests with `"type": "Collection"` according to [IIIF Presentation v3](https://iiif.io/api/presentation/3.0/#thumbnail) and [IIIF Image 2.1.1](https://iiif.io/api/image/2.1/#technical-properties).  The properties of `thumbnail` should follow the former and the properties of `thumbnail.service` should follow the latter.
2. Adds  the `summary` property to manifest with `"type": "Collection"` with the value of `\mods\abstract` as the English value.
3. Adds a `viewingDirection` of `left-to-right` to `Collection` manifests (see [here](https://iiif.io/api/presentation/3.0/#viewingdirection) for more).
4. Adds a `behavior` of `unordered` to `Collection` manifests (see [here](https://iiif.io/api/presentation/3.0/#viewingdirection) …
> Add thumbnails according to Image 2.1.1 spec to manifests.

- src/IIIF.php
1. Makes `body` a JSON-like object rather than an array.
2. Makes `service` an array of JSON-like objects.
3. Addresses [Issue 22](https://github.com/utkdigitalinitiatives/iiif_assemble/issues/22).
4. Moves captions to `annotations` property of `Canvas` following [Recipe 219: Using Caption and Subtitle Files with Video Content](https://iiif.io/api/cookbook/recipe/0219-using-caption-file/).
Our manifests are currently way out of spec.  These problems make it impossible to use community based tools like [Clover IIIF](https://github.com/samvera-labs/clover-iiif). This gets things in order so that these tools can be used.
This attempts to follow [Recipe 219: Using Caption and Subtitle Files with Video Content](https://iiif.io/api/cookbook/recipe/0219-using-caption-file/).  It's important …
> Address DIGITAL-1378.

- src/IIIF.php
Only adds `annotations` properties to Canvases if they exist.
> Address DIGITAL-1408: empty annotations.

- src/IIIF.php
- src/Request.php
- src/Utility.php
What is this change's affects on:
> Determine if the object is compound.

- src/IIIF.php
1. Implements a new pattern for embedded resources in IIIF manifests 
2. Fixes a bug where update or initial generation of manifests for audio and video manifests fail
3. Fixes another bug where range canvases reference the wrong canvas
In IIIF, a consuming application cannot assume a resource is embedded.  There is no property that specifies this, so a consuming application may dereference the id to see if there is additional information.  Currently, we have dereferenceable ids that do not represent the resource. This fixes that so that we can leverage navPlace viewer.
I wrote a whole blog post over the weekend explaining this that you can see [here](https://markpbaggett.github.io/iiif-id-property.html).
Yes, I took this to IIIF technical and this is the suggested practice.
Yes, this …
> Init refactor of non-dereferenceable ids.

- src/IIIF.php
- src/Navplace.php
1. Initializes `navPlace` on Manifests
2. Removes unused method
This allows us to have minimal navPlace bodies on manifests and think about how this should work in our future repository.  It also allows us to give feedback about [navPlace](https://github.com/CenterForDigitalHumanities/navplace-viewer/) and perhaps think about how we might use `navPlace` with something like nectar.
This adds `navPlace` only to manifests that have `subject[@authority="geonames"]/cartographics/coordinates values. This should probably be more open, but doing so requires more complicated code for very few use cases.
The `navPlace` prop is only placed on Manifest for now and gets a label equivalent to the matching string in the MODS record.  I don't think this ultimately should be the label, but this is how our …
> Remove unused method and add navPlace extension.

- src/IIIF.php
Makes our audio things work in UV 4.
Universal Viewer 4 uses a very prescriptive typing library called [Vocabulary](https://github.com/IIIF-Commons/vocabulary). Universal Viewer attempts to apply the UV experience to any file type, and because of this it expects a very specific mime type for each kind of thing. Here you can see an [example of this for MP3s](https://github.com/IIIF-Commons/vocabulary/blob/7fa2004c501c69d1ceb11bb561ce80bd8ca429b4/src/index.ts#L75).  The type enum only makes UV use the HTML 5 Audio Canvas; it doesn't actually care what the mime type is.  If there was a sound file that the audio canvas couldn't play, the browser would handle that just as it would with anything else.
> Make audio objects playable in UV4.

- src/Navplace.php
Converts all coordinates regardless of authority to navPlace bodies following current conventions.  If coords contain a string, the string is dropped. If it contains 'W' or 'S', the float becomes negative.
You could test on dlwork or review [here](https://rfta-reimagined-git-navplace-markpbaggett.vercel.app/map).  Note that the two Alumnus examples are there because I didn't force them to be updated?
We have many inaccuracies in our geospatial data.  This gives us an easy solution review that and correct.
> Convert all coordinates to navPlace.

- README.md
- src/IIIF.php
- src/Navdate.php
- src/Utility.php
This pull request really 4 things:
This adds a `navDate` property to manifests where possible. This allows us to state the chronological order of manifests in a collection object so that viewers that are setup to display a timeline work as expected.
An example of what a timeline viewer might be something like one of these:
1. https://markpbaggett.github.io/kintner_collection_builder/timeline.html
2. https://exhibits.lib.utk.edu/galston/gottfried-galston
I'm not sure why, but the SPARQL query results handled by `Utility::orderCanvases` expects a type at the fourth index value.  Looking at the rest of the code, we should be able to just declare this without the csv response. This specific method is from a very long time ago, and I'm not sure what the original author of the method was trying …
> Implement navDate and fix known validity errors on manifests.

- src/IIIF.php
- src/Navdate.php
- src/Thumbnail.php
- src/Utility.php
1. Initializes work to make thumbnail generation more sustainable.
2. Fixes an issue where an item with a `dc:title` that includes double quote got no label in the IIIF Collection object.
3. Makes it so that Works sourced from an image server don't use the Islandora generated thumbnail.
> Fix thumbnails

- src/Utility.php
This fixes the problem where labels of pages or parts of compound objects get chopped up.
> Split canvas metadata in a better way.

- src/IIIF.php
- src/MetadataProperty.php
- src/Rights.php
1. Refactors descriptive metadata into its own class.
2. Makes canvases only include descriptive metadata that is not found in the parent.
3. Fixes an old bug where rights work was written around PHP 8.
4. Writes CNE for any works without rights.
> Metadata redux
